---
- name: Provision
  hosts: mysql-master
  become: true
  tasks:
    - name: APT | Instal mysql
      apt: name=mysql-server,mysql-client
    
    - name: MYSQL | Copy test sql script to create database and tables
      copy:
        src: ../../templates/master/test.sql
        dest: /usr/local/etc/

    - name: MYSQL | Create test data base and test table
      shell:
        cmd: mysql -u root  < /usr/local/etc/test.sql

    - name: MYSQL | Copy my.cnf file
      copy:
        src: ../../templates/master/my.cnf
        dest: /etc/mysql

    - name: MYSQL | Restart mysql servie
      service:
        name: mysql
        state: restarted

    - name: MYSQL | Create slave_user user
      shell:
        cmd: mysql -u root -e "GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' IDENTIFIED BY 'slave_user'; FLUSH PRIVILEGES;"
